# Generated by Django 2.1.5 on 2019-02-05 06:33

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('featured_image', models.ImageField(default='blog_images/default.jpeg', upload_to='blog_images/')),
                ('content', tinymce.models.HTMLField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('data_published', models.DateTimeField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
