# Generated by Django 2.1.5 on 2019-02-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_create_post_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data_published',
            new_name='date_published',
        ),
    ]
