sudo: false
language: python
python:
  - "3.6"
install: pip install tox-travis
script: tox
branches:
  only:
  - master
  - heroku-deployment
matrix:
  include:
    - python: 3.6
    - env: TOXENV=lint
