sudo: false
language: python
python:
  - 3.6
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=lint
install:
  - pip install tox-travis
script:
  - tox
branches:
  only:
    - master
    - heroku-deployment
